version: "3"
services:
  proxy:
    image: nginx:alpine

    environment:
      SCHEME: https
      BACKEND: leetcode.com:443

    ports:
      - 38080:443

    volumes:
      - ./nginx-cors-proxy.conf:/etc/nginx/conf.d/default.template:ro

    command:
      - /bin/sh
      - -c
      - envsubst '$$BACKEND' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
        exec nginx-debug -g 'daemon off;'

  frontend:
    build: frontend/
    ports:
      - 8000:80
    depends_on:
      - proxy

