version: "3"
services:
  proxy:
    build: proxy/
    environment:
      PROXY_TARGET: https://leetcode.com/
    ports:
      - 38080:80

  frontend:
    build: frontend/
    ports:
      - 8000:80
    depends_on:
      - proxy
